version: '3.8'

services:
  flet-server:
    build:
      context: https://github.com/PizzaRevolutions/Thread-Chess.git#main
      dockerfile: Dockerfile
    container_name: thread-chess-server
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLET_FORCE_WEB_SERVER=true
    restart: unless-stopped
